### ISSUE TITLE
Save video

### ISSUE THREAD

**Issue by Inferencer** [htuannn/Face-Swapping#1]
Great work, suprisingly easy to install & run!

I dont see how to save a video in the video_face_swapping.py

**Comment by Inferencer** [comment]
ah I see you commented it out fixed it

**Comment by Inferencer** [comment]
i tried as .mp4 and went back to .avi it's saving the file but I cannot play it even on vlc media player

**Comment by Inferencer** [comment]
fixed again, man you commented out alot of important functions xd

**Comment by htuann2712** [comment]
> fixed again, man you commented out alot of important functions xd

haha xd sorry for that
