### ISSUE TITLE
Running on GPU

### ISSUE THREAD

**Issue by ChaeSeoyoung** [htuannn/Face-Swapping#3]
Mediapipe seems not running with GPUs on windows.
When I run the code, the speed is only 8 fps. (Since it's running on CPU) And this seems not to be real-time speed.

Could you let me know how can I run the code on linux setting with GPUs?

Thank you :)

**Comment by ChaeSeoyoung** [comment]
Also, the below link is unavailable.

https://google.github.io/mediapipe/solutions/face_mesh.html

**Comment by htuann2712** [comment]
This is a new doc from Google AI. 
https://github.com/google-ai-edge/mediapipe/blob/master/docs/solutions/face_mesh.md

 I saw them mentioning using Mediapipe Face Mesh with GPU, you can take a look.
